[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["echo 'Build phase completado'"]

[start]
cmd = "cd backend && npm start"
